USE [master]
GO

/****** Object:  Database [WoTClans]    Script Date: 8/12/2020 4:25:06 PM ******/
CREATE DATABASE [WoTClans]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'wotclans', FILENAME = N'C:\DB\WoTClans.mdf' , SIZE = 10MB , MAXSIZE = 10GB, FILEGROWTH = 10MB )
 LOG ON 
( NAME = N'wotclans_log', FILENAME = N'C:\DB\WoTClans_log.ldf' , SIZE = 1MB , MAXSIZE = 2GB, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [WoTClans] COLLATE SQL_Latin1_General_CP1_CI_AS;
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WoTClans].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WoTClans] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WoTClans] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WoTClans] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WoTClans] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WoTClans] SET ARITHABORT OFF 
GO

ALTER DATABASE [WoTClans] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WoTClans] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WoTClans] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WoTClans] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WoTClans] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WoTClans] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WoTClans] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WoTClans] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WoTClans] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WoTClans] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WoTClans] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WoTClans] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WoTClans] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WoTClans] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WoTClans] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WoTClans] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WoTClans] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WoTClans] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WoTClans] SET  MULTI_USER 
GO

ALTER DATABASE [WoTClans] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WoTClans] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WoTClans] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WoTClans] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WoTClans] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WoTClans] SET QUERY_STORE = ON
GO

ALTER DATABASE [WoTClans] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [WoTClans] SET  READ_WRITE 
GO

