//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negri.Wot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Negri.Wot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTextLink {
            get {
                return ResourceManager.GetString("AboutTextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this site.
        /// </summary>
        public static string AboutThisSite {
            get {
                return ResourceManager.GetString("AboutThisSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this tournament.
        /// </summary>
        public static string AboutTournament {
            get {
                return ResourceManager.GetString("AboutTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on Tournaments.
        /// </summary>
        public static string AboutTournamentsTextLink {
            get {
                return ResourceManager.GetString("AboutTournamentsTextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aces.
        /// </summary>
        public static string Aces {
            get {
                return ResourceManager.GetString("Aces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan&apos;s active commanders..
        /// </summary>
        public static string ActiveCommandersExplanation {
            get {
                return ResourceManager.GetString("ActiveCommandersExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actives.
        /// </summary>
        public static string Actives {
            get {
                return ResourceManager.GetString("Actives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of members with at least 21 battles in the last month..
        /// </summary>
        public static string ActivesExplanation {
            get {
                return ResourceManager.GetString("ActivesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of active players on the last month.
        /// </summary>
        public static string ActivityExplanation {
            get {
                return ResourceManager.GetString("ActivityExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request your clan inclusion.
        /// </summary>
        public static string AddYourClan {
            get {
                return ResourceManager.GetString("AddYourClan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arty.
        /// </summary>
        public static string Artillery {
            get {
                return ResourceManager.GetString("Artillery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assisted.
        /// </summary>
        public static string Assisted {
            get {
                return ResourceManager.GetString("Assisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assisted Damage.
        /// </summary>
        public static string AssistedDamage {
            get {
                return ResourceManager.GetString("AssistedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assisted Damage per Battle.
        /// </summary>
        public static string AssistedDamageExplanation {
            get {
                return ResourceManager.GetString("AssistedDamageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atack.
        /// </summary>
        public static string Atack {
            get {
                return ResourceManager.GetString("Atack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        public static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Tier.
        /// </summary>
        public static string AvgTier {
            get {
                return ResourceManager.GetString("AvgTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actives Avg Tier.
        /// </summary>
        public static string AvgTierActives {
            get {
                return ResourceManager.GetString("AvgTierActives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The average tier that was being played.
        /// </summary>
        public static string AvgTierExplanation {
            get {
                return ResourceManager.GetString("AvgTierExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 15 Avg Tier.
        /// </summary>
        public static string AvgTierTop15 {
            get {
                return ResourceManager.GetString("AvgTierTop15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles.
        /// </summary>
        public static string Battles {
            get {
                return ResourceManager.GetString("Battles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of batlles performed by active players on last month..
        /// </summary>
        public static string BattlesExplanation {
            get {
                return ResourceManager.GetString("BattlesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of battles on this data set.
        /// </summary>
        public static string BattlesStatsExplanation {
            get {
                return ResourceManager.GetString("BattlesStatsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best commander on each vehicle, calculated at {0:d}..
        /// </summary>
        public static string BestTankersAt {
            get {
                return ResourceManager.GetString("BestTankersAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The % of hits that are Blocked by Armour.
        /// </summary>
        public static string BlockedExplanation {
            get {
                return ResourceManager.GetString("BlockedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brackets.
        /// </summary>
        public static string Brackets {
            get {
                return ResourceManager.GetString("Brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Calculated at.
        /// </summary>
        public static string CalculatedAt {
            get {
                return ResourceManager.GetString("CalculatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Points per Battle.
        /// </summary>
        public static string CaptureExplanation {
            get {
                return ResourceManager.GetString("CaptureExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan.
        /// </summary>
        public static string Clan {
            get {
                return ResourceManager.GetString("Clan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for.
        /// </summary>
        public static string ClanDetail {
            get {
                return ResourceManager.GetString("ClanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status and evolution of the {0} clan in the World of Tanks game..
        /// </summary>
        public static string ClanMetaDescription {
            get {
                return ResourceManager.GetString("ClanMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan ranking (filters considered) according to WN8t15..
        /// </summary>
        public static string ClanRankingExplanation {
            get {
                return ResourceManager.GetString("ClanRankingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clans.
        /// </summary>
        public static string Clans {
            get {
                return ResourceManager.GetString("Clans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined.
        /// </summary>
        public static string Combined {
            get {
                return ResourceManager.GetString("Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Damage.
        /// </summary>
        public static string CombinedDamage {
            get {
                return ResourceManager.GetString("CombinedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sum of Direct, Tracking and Spotting Damage per Battle.
        /// </summary>
        public static string CombinedDamageExplanation {
            get {
                return ResourceManager.GetString("CombinedDamageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined DPM.
        /// </summary>
        public static string CombinedDPM {
            get {
                return ResourceManager.GetString("CombinedDPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Damage per Minute.
        /// </summary>
        public static string CombinedDPMExplanation {
            get {
                return ResourceManager.GetString("CombinedDPMExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        public static string Commander {
            get {
                return ResourceManager.GetString("Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander ranking on the clan according to the recent WN8..
        /// </summary>
        public static string CommanderRankingExplanation {
            get {
                return ResourceManager.GetString("CommanderRankingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commanders.
        /// </summary>
        public static string Commanders {
            get {
                return ResourceManager.GetString("Commanders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of players on this data set.
        /// </summary>
        public static string CommandersStatsExplanation {
            get {
                return ResourceManager.GetString("CommandersStatsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparisons.
        /// </summary>
        public static string Comparisons {
            get {
                return ResourceManager.GetString("Comparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czechoslovakia.
        /// </summary>
        public static string Czechoslovakia {
            get {
                return ResourceManager.GetString("Czechoslovakia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Damage per Battle.
        /// </summary>
        public static string DamageExplanation {
            get {
                return ResourceManager.GetString("DamageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage per Piercing.
        /// </summary>
        public static string DamagePiercing {
            get {
                return ResourceManager.GetString("DamagePiercing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Damage per Piercing.
        /// </summary>
        public static string DamagePiercingExplanation {
            get {
                return ResourceManager.GetString("DamagePiercingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Ratio.
        /// </summary>
        public static string DamageRatio {
            get {
                return ResourceManager.GetString("DamageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Direct Damage Dealt per Damage Received Ratio.
        /// </summary>
        public static string DamageRatioExplanation {
            get {
                return ResourceManager.GetString("DamageRatioExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Received.
        /// </summary>
        public static string DamageReceived {
            get {
                return ResourceManager.GetString("DamageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Received per Battle.
        /// </summary>
        public static string DamageReceivedExplanation {
            get {
                return ResourceManager.GetString("DamageReceivedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data obtained under the kind permission of.
        /// </summary>
        public static string DataPermission {
            get {
                return ResourceManager.GetString("DataPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retrieved at {0:O}..
        /// </summary>
        public static string DataRetrievedAt {
            get {
                return ResourceManager.GetString("DataRetrievedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retrieved at {0:O}, next update ~{1:O}..
        /// </summary>
        public static string DataRetrievedAtNextAt {
            get {
                return ResourceManager.GetString("DataRetrievedAtNextAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One day before data..
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string DayAbbr {
            get {
                return ResourceManager.GetString("DayAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Ago.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time that the tank was played.
        /// </summary>
        public static string DaysStatsExplanation {
            get {
                return ResourceManager.GetString("DaysStatsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value variation..
        /// </summary>
        public static string DeltaExplanation {
            get {
                return ResourceManager.GetString("DeltaExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string Direct {
            get {
                return ResourceManager.GetString("Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Bot.
        /// </summary>
        public static string DiscordBot {
            get {
                return ResourceManager.GetString("DiscordBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string Discussion {
            get {
                return ResourceManager.GetString("Discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate!.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate with Crypto Currencies.
        /// </summary>
        public static string DonateCrypto {
            get {
                return ResourceManager.GetString("DonateCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help me keep this site ad free!.
        /// </summary>
        public static string DonateExplain {
            get {
                return ResourceManager.GetString("DonateExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate with PayPal.
        /// </summary>
        public static string DonatePayPal {
            get {
                return ResourceManager.GetString("DonatePayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPM.
        /// </summary>
        public static string DPM {
            get {
                return ResourceManager.GetString("DPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Damage per Minute.
        /// </summary>
        public static string DPMExplanation {
            get {
                return ResourceManager.GetString("DPMExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP/min.
        /// </summary>
        public static string DPMUnit {
            get {
                return ResourceManager.GetString("DPMUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped Capture.
        /// </summary>
        public static string DroppedCapture {
            get {
                return ResourceManager.GetString("DroppedCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped Capture Points per Battle.
        /// </summary>
        public static string DroppedCaptureExplanation {
            get {
                return ResourceManager.GetString("DroppedCaptureExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolution.
        /// </summary>
        public static string Evolution {
            get {
                return ResourceManager.GetString("Evolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN8&apos;s value.
        /// </summary>
        public static string EvolutionAxisTitle {
            get {
                return ResourceManager.GetString("EvolutionAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Expected Values per Battle.
        /// </summary>
        public static string ExpectedValues {
            get {
                return ResourceManager.GetString("ExpectedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosion Hits.
        /// </summary>
        public static string ExplosionHits {
            get {
                return ResourceManager.GetString("ExplosionHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosion Hits per Battle.
        /// </summary>
        public static string ExplosionHitsExplanation {
            get {
                return ResourceManager.GetString("ExplosionHitsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosion Hits Received.
        /// </summary>
        public static string ExplosionHitsReceived {
            get {
                return ResourceManager.GetString("ExplosionHitsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosion Hits Received per Battle.
        /// </summary>
        public static string ExplosionHitsReceivedExplanation {
            get {
                return ResourceManager.GetString("ExplosionHitsReceivedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all active (at least 7 active players on the last month) clans..
        /// </summary>
        public static string FilterAllExplanation {
            get {
                return ResourceManager.GetString("FilterAllExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Clans.
        /// </summary>
        public static string FilterBig {
            get {
                return ResourceManager.GetString("FilterBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show clans with at least 15 active players..
        /// </summary>
        public static string FilterBigExplanation {
            get {
                return ResourceManager.GetString("FilterBigExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By country.
        /// </summary>
        public static string FilterByCountry {
            get {
                return ResourceManager.GetString("FilterByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by &quot;country&quot;.
        /// </summary>
        public static string FilterByCountryExplanation {
            get {
                return ResourceManager.GetString("FilterByCountryExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string FilterDefault {
            get {
                return ResourceManager.GetString("FilterDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all filters and revert to the default view..
        /// </summary>
        public static string FilterDefaultExplanation {
            get {
                return ResourceManager.GetString("FilterDefaultExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Clans.
        /// </summary>
        public static string FilterSmall {
            get {
                return ResourceManager.GetString("FilterSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show clans with less than 15 active players..
        /// </summary>
        public static string FilterSmallExplanation {
            get {
                return ResourceManager.GetString("FilterSmallExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for PlayStation.
        /// </summary>
        public static string ForPs {
            get {
                return ResourceManager.GetString("ForPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for XBOX.
        /// </summary>
        public static string ForXbox {
            get {
                return ResourceManager.GetString("ForXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Active Commanders.
        /// </summary>
        public static string FrequencyAxisActives {
            get {
                return ResourceManager.GetString("FrequencyAxisActives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Battles.
        /// </summary>
        public static string FrequencyAxisBattles {
            get {
                return ResourceManager.GetString("FrequencyAxisBattles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string Heavy {
            get {
                return ResourceManager.GetString("Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic.
        /// </summary>
        public static string Historic {
            get {
                return ResourceManager.GetString("Historic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last 2 months..
        /// </summary>
        public static string HistoricExplanation {
            get {
                return ResourceManager.GetString("HistoricExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Ratio.
        /// </summary>
        public static string HitRatio {
            get {
                return ResourceManager.GetString("HitRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Shots that Hits the Target.
        /// </summary>
        public static string HitRatioExplanation {
            get {
                return ResourceManager.GetString("HitRatioExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits per Battle.
        /// </summary>
        public static string HitsExplanation {
            get {
                return ResourceManager.GetString("HitsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits Received.
        /// </summary>
        public static string HitsReceived {
            get {
                return ResourceManager.GetString("HitsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Hits Received per Battle.
        /// </summary>
        public static string HitsReceivedExplanation {
            get {
                return ResourceManager.GetString("HitsReceivedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        public static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills/Deaths.
        /// </summary>
        public static string KillDeath {
            get {
                return ResourceManager.GetString("KillDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills for each Death on the Tank.
        /// </summary>
        public static string KillDeathExplanation {
            get {
                return ResourceManager.GetString("KillDeathExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        public static string Kills {
            get {
                return ResourceManager.GetString("Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills per Battle.
        /// </summary>
        public static string KillsExplanation {
            get {
                return ResourceManager.GetString("KillsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actually, it&apos;s 28 days, 4 weeks..
        /// </summary>
        public static string LastMonthExplanation {
            get {
                return ResourceManager.GetString("LastMonthExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string Leaderboard {
            get {
                return ResourceManager.GetString("Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bit more damage to the Leaderboard!.
        /// </summary>
        public static string LeaderIfFewMoreDamage {
            get {
                return ResourceManager.GetString("LeaderIfFewMoreDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Do more &lt;b&gt;damage&lt;/b&gt; (less than 5% increase) on the following tanks, before &lt;span class=&quot;universal-time-text&quot;&gt;{0:O}&lt;/span&gt;, to have a chance to appear on the leaderboard:&lt;/p&gt;.
        /// </summary>
        public static string LeaderIfFewMoreDamageExplanation {
            get {
                return ResourceManager.GetString("LeaderIfFewMoreDamageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few more battles to the Leaderboard!.
        /// </summary>
        public static string LeaderIfFewMoreGames {
            get {
                return ResourceManager.GetString("LeaderIfFewMoreGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Play &lt;b&gt;just a few&lt;/b&gt; (up to 10) &lt;i&gt;good&lt;/i&gt; battles on the following tanks, before &lt;span class=&quot;universal-time-text&quot;&gt;{0:O}&lt;/span&gt;, to have a chance to appear on the leaderboard:&lt;/p&gt;.
        /// </summary>
        public static string LeaderIfFewMoreGamesExplanation {
            get {
                return ResourceManager.GetString("LeaderIfFewMoreGamesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get back on the Leaderboard!.
        /// </summary>
        public static string LeaderIfPlayABattle {
            get {
                return ResourceManager.GetString("LeaderIfPlayABattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Play at least &lt;b&gt;one&lt;/b&gt; &lt;i&gt;good&lt;/i&gt; battle on the following tanks, before &lt;span class=&quot;universal-time-text&quot;&gt;{0:O}&lt;/span&gt;, to have a chance to appear &lt;b&gt;again&lt;/b&gt; on the leaderboard:&lt;/p&gt;.
        /// </summary>
        public static string LeaderIfPlayABattleExplanation {
            get {
                return ResourceManager.GetString("LeaderIfPlayABattleExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome to the Leaderboard!.
        /// </summary>
        public static string LeaderOnNextUpdate {
            get {
                return ResourceManager.GetString("LeaderOnNextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;It&apos;s very likely (but there is no guarantee) that on the next calculation of the leaderbord, at &lt;span class=&quot;universal-time-text&quot;&gt;{0:O}&lt;/span&gt;, these tanks will appear on the leaderboard:&lt;/p&gt;.
        /// </summary>
        public static string LeaderOnNextUpdateExplanation {
            get {
                return ResourceManager.GetString("LeaderOnNextUpdateExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaders.
        /// </summary>
        public static string Leaders {
            get {
                return ResourceManager.GetString("Leaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Tanks&apos; Clans.
        /// </summary>
        public static string MainSiteTitle {
            get {
                return ResourceManager.GetString("MainSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastery.
        /// </summary>
        public static string Mastery {
            get {
                return ResourceManager.GetString("Mastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Mastery of the Players: 4 is Ace.
        /// </summary>
        public static string MasteryExplanation {
            get {
                return ResourceManager.GetString("MasteryExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Kills.
        /// </summary>
        public static string MaxKills {
            get {
                return ResourceManager.GetString("MaxKills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Max Kills per Commander.
        /// </summary>
        public static string MaxKillsExplanation {
            get {
                return ResourceManager.GetString("MaxKillsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of clan&apos;s members..
        /// </summary>
        public static string MembersExplanation {
            get {
                return ResourceManager.GetString("MembersExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercenaries.
        /// </summary>
        public static string Mercenaries {
            get {
                return ResourceManager.GetString("Mercenaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoT Clans tracks the status and evolution of the clans in the game World of Tanks {0}..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string Metric {
            get {
                return ResourceManager.GetString("Metric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks of Excellence.
        /// </summary>
        public static string MoE {
            get {
                return ResourceManager.GetString("MoE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Mark.
        /// </summary>
        public static string MoE1Mark {
            get {
                return ResourceManager.GetString("MoE1Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Marks.
        /// </summary>
        public static string MoE2Mark {
            get {
                return ResourceManager.GetString("MoE2Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Marks.
        /// </summary>
        public static string MoE3Mark {
            get {
                return ResourceManager.GetString("MoE3Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for {0:N0} tanks calculated at {1:d}..
        /// </summary>
        public static string MoEData {
            get {
                return ResourceManager.GetString("MoEData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks of Excellence for World of Tanks {0}.
        /// </summary>
        public static string MoEDescriptions {
            get {
                return ResourceManager.GetString("MoEDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The estimated &lt;b&gt;Combined Damage&lt;/b&gt; (the sum of Direct and Assited Damage) that you should achieve to get &lt;b&gt;Marks of Excelence&lt;/b&gt; on the barrel of your cannon..
        /// </summary>
        public static string MoEExplanation {
            get {
                return ResourceManager.GetString("MoEExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Tank, Type or Nation:.
        /// </summary>
        public static string MoEFilter {
            get {
                return ResourceManager.GetString("MoEFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Damage estimates to achieve MoEs.
        /// </summary>
        public static string MoESubTitle {
            get {
                return ResourceManager.GetString("MoESubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One month before data..
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string MonthAbbr {
            get {
                return ResourceManager.GetString("MonthAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string Nation {
            get {
                return ResourceManager.GetString("Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On last month..
        /// </summary>
        public static string OnLastMonth {
            get {
                return ResourceManager.GetString("OnLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrapolation.
        /// </summary>
        public static string OriginExtrapolated {
            get {
                return ResourceManager.GetString("OriginExtrapolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string OriginSource {
            get {
                return ResourceManager.GetString("OriginSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrogate.
        /// </summary>
        public static string OriginSurrogate {
            get {
                return ResourceManager.GetString("OriginSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Surrogates.
        /// </summary>
        public static string OriginSurrogateTwo {
            get {
                return ResourceManager.GetString("OriginSurrogateTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier/Type.
        /// </summary>
        public static string OriginTierType {
            get {
                return ResourceManager.GetString("OriginTierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        public static string Overall {
            get {
                return ResourceManager.GetString("Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall number of battles of the entire clan..
        /// </summary>
        public static string OverallBattlesExplanation {
            get {
                return ResourceManager.GetString("OverallBattlesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall stats for {0} [{1}].
        /// </summary>
        public static string OverallStatsForPlayer {
            get {
                return ResourceManager.GetString("OverallStatsForPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Overall&lt;/b&gt; data retrieved at &lt;span class=&quot;universal-time-text&quot;&gt;{0:O}&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string OverallStatsForPlayerMoment {
            get {
                return ResourceManager.GetString("OverallStatsForPlayerMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of victories, on weighted average, that all players achieved..
        /// </summary>
        public static string OverallWinRateExplanation {
            get {
                return ResourceManager.GetString("OverallWinRateExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN8, on weighted average, that all players achieved..
        /// </summary>
        public static string OverallWn8Explanation {
            get {
                return ResourceManager.GetString("OverallWn8Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercing Ratio.
        /// </summary>
        public static string PiercingRatio {
            get {
                return ResourceManager.GetString("PiercingRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of the Hits that Pierces the Target.
        /// </summary>
        public static string PiercingRatioExplanation {
            get {
                return ResourceManager.GetString("PiercingRatioExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercings.
        /// </summary>
        public static string Piercings {
            get {
                return ResourceManager.GetString("Piercings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercings per Battle.
        /// </summary>
        public static string PiercingsExplanation {
            get {
                return ResourceManager.GetString("PiercingsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercings/Shots Ratio.
        /// </summary>
        public static string PiercingShotRatio {
            get {
                return ResourceManager.GetString("PiercingShotRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of the Shots that Pierces the Target.
        /// </summary>
        public static string PiercingShotRatioExplanation {
            get {
                return ResourceManager.GetString("PiercingShotRatioExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercings Received.
        /// </summary>
        public static string PiercingsReceived {
            get {
                return ResourceManager.GetString("PiercingsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piercings Received per Battle.
        /// </summary>
        public static string PiercingsReceivedExplanation {
            get {
                return ResourceManager.GetString("PiercingsReceivedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players updated every ~{0:N0}h on average..
        /// </summary>
        public static string PlayersUpdatedEvery {
            get {
                return ResourceManager.GetString("PlayersUpdatedEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active commanders on each rating..
        /// </summary>
        public static string RatingActiveExplanation {
            get {
                return ResourceManager.GetString("RatingActiveExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of active commanders on this rating..
        /// </summary>
        public static string RatingActiveNumberExplanation {
            get {
                return ResourceManager.GetString("RatingActiveNumberExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battles performed by commandes on each rating..
        /// </summary>
        public static string RatingBattleExplanation {
            get {
                return ResourceManager.GetString("RatingBattleExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of battles performed by active commanders on this rating..
        /// </summary>
        public static string RatingBattleNumberExplanation {
            get {
                return ResourceManager.GetString("RatingBattleNumberExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Distribuction.
        /// </summary>
        public static string RatingDistribuction {
            get {
                return ResourceManager.GetString("RatingDistribuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN8a rating..
        /// </summary>
        public static string RatingExplanation {
            get {
                return ResourceManager.GetString("RatingExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of active commandets on this rating..
        /// </summary>
        public static string RatingPercentActiveExplanation {
            get {
                return ResourceManager.GetString("RatingPercentActiveExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of battles performed by active commanders on this rating..
        /// </summary>
        public static string RatingPercentBattlesExplanation {
            get {
                return ResourceManager.GetString("RatingPercentBattlesExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent stats for {0} [{1}].
        /// </summary>
        public static string RecentStatsForPlayer {
            get {
                return ResourceManager.GetString("RecentStatsForPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Recent&lt;/b&gt; data retrieved at &lt;span class=&quot;universal-time-text&quot;&gt;{0:O}&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string RecentStatsForPlayerMoment {
            get {
                return ResourceManager.GetString("RecentStatsForPlayerMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See PlayStation&apos;s Clans.
        /// </summary>
        public static string SeePlayStationClans {
            get {
                return ResourceManager.GetString("SeePlayStationClans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See XBOX&apos;s Clans.
        /// </summary>
        public static string SeeXboxClans {
            get {
                return ResourceManager.GetString("SeeXboxClans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots.
        /// </summary>
        public static string Shots {
            get {
                return ResourceManager.GetString("Shots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shots per Battles.
        /// </summary>
        public static string ShotsExplanation {
            get {
                return ResourceManager.GetString("ShotsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Less.
        /// </summary>
        public static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Top 15.
        /// </summary>
        public static string ShowTop15 {
            get {
                return ResourceManager.GetString("ShowTop15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotting Damage.
        /// </summary>
        public static string SpotDamage {
            get {
                return ResourceManager.GetString("SpotDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotting Damage per Battle.
        /// </summary>
        public static string SpotDamageExplanation {
            get {
                return ResourceManager.GetString("SpotDamageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotted.
        /// </summary>
        public static string Spoted {
            get {
                return ResourceManager.GetString("Spoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotted.
        /// </summary>
        public static string Spotted {
            get {
                return ResourceManager.GetString("Spotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotted Tanks per Battle.
        /// </summary>
        public static string SpottedExplanation {
            get {
                return ResourceManager.GetString("SpottedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for the &lt;a href=&quot;https://console.worldoftanks.com/encyclopedia/vehicles/{6}/{7}&quot;&gt;{0}&lt;/a&gt;, {1}Tier {2}, {3}, {4}, calculated at {5:d}.
        /// </summary>
        public static string StatsBanner1 {
            get {
                return ResourceManager.GetString("StatsBanner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is computed every week, using the battles of the clan&apos;s members that this site tracks. This is not the whole picture, be advised..
        /// </summary>
        public static string StatsBanner2 {
            get {
                return ResourceManager.GetString("StatsBanner2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for the {0} - WoT {1}.
        /// </summary>
        public static string StatsDesc {
            get {
                return ResourceManager.GetString("StatsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for the {0}.
        /// </summary>
        public static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival Rate.
        /// </summary>
        public static string SurvivalRate {
            get {
                return ResourceManager.GetString("SurvivalRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Battles that the Tank Survives.
        /// </summary>
        public static string SurvivalRateExplanation {
            get {
                return ResourceManager.GetString("SurvivalRateExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are commanders with suspect data..
        /// </summary>
        public static string SuspectData {
            get {
                return ResourceManager.GetString("SuspectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to me on Discord (English).
        /// </summary>
        public static string TalkToMeDiscord {
            get {
                return ResourceManager.GetString("TalkToMeDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        public static string TankDestroyer {
            get {
                return ResourceManager.GetString("TankDestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanks.
        /// </summary>
        public static string Tanks {
            get {
                return ResourceManager.GetString("Tanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Damage.
        /// </summary>
        public static string TargetDamage {
            get {
                return ResourceManager.GetString("TargetDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string Tier {
            get {
                return ResourceManager.GetString("Tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time per Battle.
        /// </summary>
        public static string TimePerBattle {
            get {
                return ResourceManager.GetString("TimePerBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of each battle.
        /// </summary>
        public static string TimePerBattleExplanation {
            get {
                return ResourceManager.GetString("TimePerBattleExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time per Player.
        /// </summary>
        public static string TimePerPlayer {
            get {
                return ResourceManager.GetString("TimePerPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time that each commander played on this tank.
        /// </summary>
        public static string TimePerPlayerExplanation {
            get {
                return ResourceManager.GetString("TimePerPlayerExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournaments.
        /// </summary>
        public static string Tournaments {
            get {
                return ResourceManager.GetString("Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Damage.
        /// </summary>
        public static string TrackDamage {
            get {
                return ResourceManager.GetString("TrackDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Damage per Battle.
        /// </summary>
        public static string TrackDamageExplanation {
            get {
                return ResourceManager.GetString("TrackDamageExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking {0:N0} commanders in {1:N0} clans..
        /// </summary>
        public static string Tracking {
            get {
                return ResourceManager.GetString("Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trees Cut.
        /// </summary>
        public static string TreesCut {
            get {
                return ResourceManager.GetString("TreesCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t drink and Drive.
        /// </summary>
        public static string TreesCutJoke {
            get {
                return ResourceManager.GetString("TreesCutJoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trees/Battle.
        /// </summary>
        public static string TreesCutUnit {
            get {
                return ResourceManager.GetString("TreesCutUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK.
        /// </summary>
        public static string Uk {
            get {
                return ResourceManager.GetString("Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated at.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string Usa {
            get {
                return ResourceManager.GetString("Usa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USSR.
        /// </summary>
        public static string Ussr {
            get {
                return ResourceManager.GetString("Ussr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a message you should read....
        /// </summary>
        public static string WarningsCall {
            get {
                return ResourceManager.GetString("WarningsCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One week before data..
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string WeekAbbr {
            get {
                return ResourceManager.GetString("WeekAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander&apos;s relative weight on the clan&apos;s WN8t15..
        /// </summary>
        public static string WeightExplanation {
            get {
                return ResourceManager.GetString("WeightExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Rate.
        /// </summary>
        public static string WinRate {
            get {
                return ResourceManager.GetString("WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of victories, on weighted average, that all active players achieved on last month..
        /// </summary>
        public static string WinRateExplanation {
            get {
                return ResourceManager.GetString("WinRateExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of Victories.
        /// </summary>
        public static string WinRateStatsExplanation {
            get {
                return ResourceManager.GetString("WinRateStatsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN8.
        /// </summary>
        public static string WN8 {
            get {
                return ResourceManager.GetString("WN8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Average.
        /// </summary>
        public static string Wn8AboveAverage {
            get {
                return ResourceManager.GetString("Wn8AboveAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN8, on weighted average, that all active players achieved on last month..
        /// </summary>
        public static string Wn8aExplanation {
            get {
                return ResourceManager.GetString("Wn8aExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Wn8Average {
            get {
                return ResourceManager.GetString("Wn8Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Wn8Bad {
            get {
                return ResourceManager.GetString("Wn8Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Average.
        /// </summary>
        public static string Wn8BelowAverage {
            get {
                return ResourceManager.GetString("Wn8BelowAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for {0:N0} tanks from {1}, version {2}, retrieved at {3:d}..
        /// </summary>
        public static string WN8DataInfo {
            get {
                return ResourceManager.GetString("WN8DataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Wn8Good {
            get {
                return ResourceManager.GetString("Wn8Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great.
        /// </summary>
        public static string Wn8Great {
            get {
                return ResourceManager.GetString("Wn8Great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average WN8.
        /// </summary>
        public static string Wn8StatsAverage {
            get {
                return ResourceManager.GetString("Wn8StatsAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Values for Computing WN8.
        /// </summary>
        public static string WN8SubTitle {
            get {
                return ResourceManager.GetString("WN8SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Unicum.
        /// </summary>
        public static string Wn8SuperUnicum {
            get {
                return ResourceManager.GetString("Wn8SuperUnicum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN8, on weighted average, that the top 15 active players (by last month WN8) achieved on last month..
        /// </summary>
        public static string Wn8t15Explanation {
            get {
                return ResourceManager.GetString("Wn8t15Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN8, on weighted average, that the top 7 active players (by last month WN8) achieved on last month..
        /// </summary>
        public static string Wn8T7Explanation {
            get {
                return ResourceManager.GetString("Wn8T7Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WN8 Expected Values.
        /// </summary>
        public static string WN8Title {
            get {
                return ResourceManager.GetString("WN8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicum.
        /// </summary>
        public static string Wn8Unicum {
            get {
                return ResourceManager.GetString("Wn8Unicum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Bad.
        /// </summary>
        public static string Wn8VeryBad {
            get {
                return ResourceManager.GetString("Wn8VeryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string Wn8VeryGood {
            get {
                return ResourceManager.GetString("Wn8VeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wot Clans by.
        /// </summary>
        public static string WotClansBy {
            get {
                return ResourceManager.GetString("WotClansBy", resourceCulture);
            }
        }
    }
}
